{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fuelsense.fullname" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      {{- include "fuelsense.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
