from django.db.models.base import Model

class ValidationError(Exception):
    def __init__(self, detail: object) -> None: ...

class Field:
    def __init__(self, *args: object, **kwargs: object) -> None: ...

class IntegerField(Field): ...
class CharField(Field): ...
class ChoiceField(Field): ...
class ListField(Field): ...
class FloatField(Field): ...
class SerializerMethodField(Field): ...

class Serializer[VT]:
    validated_data: VT
    data: dict[str, object]

    def __init__(
        self,
        instance: object = ...,
        data: object = ...,
        *,
        many: bool = ...,
        **kwargs: object,
    ) -> None: ...
    def is_valid(self, *, raise_exception: bool = ...) -> bool: ...

class ModelSerializer[MT: Model](Serializer[dict[str, object]]): ...
