from pathlib import Path

import numpy as np

from . import nn

class Tensor:
    ndim: int
    shape: tuple[int, ...]
    dtype: object
    device: object

    def to(self, *, device: object = ..., dtype: object = ...) -> Tensor: ...
    def permute(self, *dims: int) -> Tensor: ...
    def view(self, *shape: int) -> Tensor: ...
    def reshape(self, *shape: int) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def detach(self) -> Tensor: ...
    def cpu(self) -> Tensor: ...
    def numpy(self) -> np.ndarray: ...
    def mean(self) -> Tensor: ...
    def item(self) -> float: ...
    def __getitem__(self, key: object) -> Tensor: ...
    def __add__(self, other: object) -> Tensor: ...
    def __sub__(self, other: object) -> Tensor: ...
    def __rsub__(self, other: object) -> Tensor: ...
    def __mul__(self, other: object) -> Tensor: ...
    def __rmul__(self, other: object) -> Tensor: ...
    def __truediv__(self, other: object) -> Tensor: ...
    def __pow__(self, exponent: object) -> Tensor: ...

class _NoGradContext:
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...

float32: object

def tensor(data: object, *, dtype: object = ...) -> Tensor: ...
def as_tensor(data: object, *, dtype: object = ...) -> Tensor: ...
def maximum(first: Tensor, other: Tensor) -> Tensor: ...
def save(obj: object, f: str | Path) -> None: ...
def load(f: str | Path, map_location: object = ...) -> dict[str, object]: ...
def no_grad() -> _NoGradContext: ...

__all__ = ["Tensor", "as_tensor", "float32", "load", "maximum", "nn", "no_grad", "save", "tensor"]
