# ruff: noqa: N802

class _Utilization:
    gpu: int

def nvmlInit() -> None: ...
def nvmlShutdown() -> None: ...
def nvmlDeviceGetHandleByIndex(index: int) -> object: ...
def nvmlDeviceGetName(handle: object) -> bytes | str: ...
def nvmlDeviceGetUtilizationRates(handle: object) -> _Utilization: ...
