import numpy as np

class IsolationForest:
    def __init__(self, **kwargs: object) -> None: ...
    def fit(self, x: np.ndarray) -> IsolationForest: ...
    def predict(self, x: np.ndarray) -> np.ndarray: ...

class RandomForestClassifier:
    def __init__(self, **kwargs: object) -> None: ...
    def fit(self, x: np.ndarray, y: np.ndarray) -> RandomForestClassifier: ...
    def predict(self, x: np.ndarray) -> np.ndarray: ...
    def predict_proba(self, x: np.ndarray) -> np.ndarray: ...
