# ruff: noqa: N802

class RoutingIndexManager:
    def __init__(self, num_nodes: int, num_vehicles: int, depot: int) -> None: ...
    def IndexToNode(self, index: int) -> int: ...
    def NodeToIndex(self, node: int) -> int: ...
    def GetNumberOfNodes(self) -> int: ...

class Assignment:
    def Value(self, variable: IntVar) -> int: ...
    def ObjectiveValue(self) -> int: ...

class IntVar:
    def SetRange(self, min_value: int, max_value: int) -> None: ...

class RoutingDimension:
    def CumulVar(self, index: int) -> IntVar: ...

class RoutingModel:
    def __init__(self, manager: RoutingIndexManager) -> None: ...
    def RegisterTransitCallback(self, callback: object) -> int: ...
    def RegisterUnaryTransitCallback(self, callback: object) -> int: ...
    def SetArcCostEvaluatorOfVehicle(self, evaluator_index: int, vehicle: int) -> None: ...
    def AddDimensionWithVehicleCapacity(
        self,
        evaluator_index: int,
        slack_max: int,
        vehicle_capacities: list[int],
        fix_start_cumul_to_zero: bool,
        name: str,
    ) -> None: ...
    def AddDimension(
        self,
        evaluator_index: int,
        slack_max: int,
        capacity: int,
        fix_start_cumul_to_zero: bool,
        name: str,
    ) -> None: ...
    def GetDimensionOrDie(self, name: str) -> RoutingDimension: ...
    def Start(self, vehicle: int) -> int: ...
    def IsEnd(self, index: int) -> bool: ...
    def NextVar(self, index: int) -> IntVar: ...
    def SolveWithParameters(self, parameters: object) -> Assignment | None: ...

class _DefaultRoutingSearchParameters:
    first_solution_strategy: int
    local_search_metaheuristic: int
    time_limit: _Duration

class _Duration:
    def FromMilliseconds(self, ms: int) -> None: ...

def DefaultRoutingSearchParameters() -> _DefaultRoutingSearchParameters: ...
