apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fuelsense.fullname" . }}-celery-default
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.celery.default.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: celery-default
      {{- include "fuelsense.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: celery-default
        {{- include "fuelsense.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: worker-default
          image: {{ include "fuelsense.image" (dict "Values" .Values "image" .Values.django.image) }}
          command: ["celery", "-A", "fuelsense", "worker", "-Q", "default", "--loglevel=info", "-c", "{{ .Values.celery.default.concurrency }}"]
          envFrom:
            - configMapRef:
                name: {{ include "fuelsense.fullname" . }}-config
            - secretRef:
                name: {{ include "fuelsense.fullname" . }}-secret
          livenessProbe:
            exec:
              command: ["sh", "-c", "celery -A fuelsense inspect ping -d celery@$(hostname) | grep -q pong"]
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.celery.default.resources | nindent 12 }}
