apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- if .Values.serviceMesh.enabled }}
    istio-injection: enabled
    {{- end }}
    {{- include "fuelsense.labels" . | nindent 4 }}
