apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fuelsense.fullname" . }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "fuelsense.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc | quote }}
